// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uimwsuqaotboepbuflio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpbXdzdXFhb3Rib2VwYnVmbGlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxNDAwMzcsImV4cCI6MjA1MzcxNjAzN30.QBwe0Po9HjIbg83yWoDLQdk7J6J_lZ5oIISuN-H9kqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);